services:
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/school
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./web:/app

volumes:
  mongo_data:
